# Generated by Django 3.0.2 on 2020-06-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='unemployed', max_length=30),
        ),
    ]
