# Generated by Django 3.0.2 on 2020-06-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200605_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otherSkill',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
