# Generated by Django 3.0.2 on 2020-07-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_otherskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_ad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='yearly_ad',
            field=models.BooleanField(default=False),
        ),
    ]
