# Generated by Django 3.0.2 on 2020-08-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200731_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_expiry',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='yearly_expiry',
            field=models.DateField(null=True),
        ),
    ]
