# Generated by Django 3.0.2 on 2020-08-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200803_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='monthly_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yearly_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
