# Generated by Django 3.0.2 on 2020-07-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
    ]
