# Generated by Django 3.0.2 on 2020-07-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0003_auto_20200629_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
