# Generated by Django 3.0.2 on 2020-07-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0004_ads_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_sub', models.IntegerField(default=200)),
                ('monthly_sub', models.IntegerField(default=500)),
                ('yearly_sub', models.IntegerField(default=5000)),
            ],
        ),
    ]
