# Generated by Django 3.0.2 on 2020-07-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0005_pricing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pricing',
        ),
        migrations.AddField(
            model_name='ads',
            name='monthly_sub',
            field=models.IntegerField(blank=True, default=500),
        ),
        migrations.AddField(
            model_name='ads',
            name='weekly_sub',
            field=models.IntegerField(blank=True, default=200),
        ),
        migrations.AddField(
            model_name='ads',
            name='yearly_sub',
            field=models.IntegerField(blank=True, default=5000),
        ),
        migrations.AlterField(
            model_name='ads',
            name='category',
            field=models.CharField(choices=[('jobs', 'jobs'), ('pets', 'pets'), ('services', 'services'), ('real estate', 'real estate'), ('vehicles', 'vehicles'), ('fashion', 'fashion'), ('products', 'products')], default='jobs', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
