# Generated by Django 3.0.2 on 2020-07-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0006_auto_20200705_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='monthly_sub',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='weekly_sub',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='yearly_sub',
        ),
        migrations.AddField(
            model_name='ads',
            name='suscriptions',
            field=models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='weekly', max_length=20),
        ),
    ]
