# Generated by Django 3.0.2 on 2020-07-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0007_auto_20200705_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='slug',
            field=models.SlugField(max_length=200, unique_for_date='created'),
        ),
    ]
