# Generated by Django 3.0.2 on 2020-07-09 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ads', '0009_auto_20200707_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='suscriptions',
        ),
        migrations.AlterField(
            model_name='ads',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_plan', models.BooleanField(default=True)),
                ('weekly_plan', models.BooleanField(default=False)),
                ('monthly_plan', models.BooleanField(default=False)),
                ('yearly_plan', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ads',
            name='plans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='Ads.Plans'),
        ),
    ]
