# Generated by Django 3.0.2 on 2020-07-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0010_auto_20200709_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='plans',
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
    ]
