# Generated by Django 3.0.2 on 2020-07-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0011_auto_20200709_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='ad_name',
        ),
        migrations.AddField(
            model_name='ads',
            name='adname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='slug',
            field=models.SlugField(max_length=100, unique_for_date='created'),
        ),
    ]
