# Generated by Django 3.0.2 on 2020-07-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0013_auto_20200709_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='category',
            field=models.CharField(choices=[('jobs', 'jobs'), ('pets', 'pets'), ('services', 'services'), ('real estate', 'real estate'), ('vehicles', 'vehicles'), ('fashion', 'fashion'), ('products', 'products')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ads',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
